os: linux
dist: focal
arch: ppc64le
sudo: required
language: go

go: "1.15.x"

install:
  - sudo apt update
  - sudo apt-get install -y make git gcc build-essential libc6-dev libglib2.0-dev pkg-config make runc python3

script:
  - git clone https://github.com/containers/conmon.git
  - cd conmon
  - make
  - make test
  - cd bin
  - ./conmon --version
